### ISSUE TITLE
Conflicting information on License page

### ISSUE THREAD

**Issue by Jaknil** [satstep/satstep6600#1]
The license header says: 
Creative Commons Attribution Share Alike 4.0 
but the text file is for the 
Creative commons Attribution-**NonCommercial**-ShareAlike 4.0

Which one is it you want to use? 

My vote is on not restricting Commercial use since that makes it really hard to use it other contexts.
"NC licenses do not qualify as “open licenses” under the Open Definition, and works licensed under an NC license are not considered Free Cultural Works. This may be important if you want others to further distribute your work on Wikipedia, Wikimedia Commons, or other platforms requiring a license that meets the Open Definition or the Definition of Free Cultural Works." //https://wiki.creativecommons.org/wiki/NonCommercial_interpretation

**Comment by satshas** [comment]
Hi @Jaknil,
thanks for the checking.

Anyway did you opened the LICENSE file?

I think it is the correct one but for some reason the parser of Github says it's "Creative Commons Attribution Share Alike 4.0" instead of "Attribution-NonCommercial-ShareAlike 4.0 International"

I checked the content and only the formatting is different in comparison to the https://creativecommons.org/licenses/by-nc/4.0/legalcode.txt , so maybe this is the reason.
